var arines = {
  type: "Support",
  range: ["next", "H1"],
  support: 164.96,
  hp: 2343,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 2343,
  currentHp: 2343,
  def: 5,
  cRate: 0,
  cDmg: 0,
  agi: 5,
  permDmgReduc: 0,
  addDmgReduc: 0,
  immunity: [false, false, false, false],
  prohibition: [false, false],
  dpsBuff: [40, 5, 0],
  healBuff: [null, 0],
  dmgReducBuff: 15
};

var asera = {
  type: "Support",
  range: ["next", "H1"],
  support: 164.96,
  hp: 1733,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 1733,
  currentHp: 1733,
  def: 0,
  cRate: 0,
  cDmg: 0,
  agi: 5,
  permDmgReduc: 0,
  addDmgReduc: 0,
  immunity: [false, false, false, false],
  prohibition: [false, false],
  dpsBuff: [0, 0, 0],
  healBuff: ["target", 10],
  dmgReducBuff: 0
};

var clarice = {
  type: "Support",
  range: ["next", "H1"],
  support: 164.96,
  hp: 1733,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 1733,
  currentHp: 1733,
  def: 0,
  cRate: 0,
  cDmg: 0,
  agi: 5,
  permDmgReduc: 0,
  addDmgReduc: 0,
  immunity: [false, false, false, false],
  prohibition: [false, false],
  dpsBuff: [0, 0, 0],
  healBuff: [null, 0],
  dmgReducBuff: 32
};

var edan = {
  type: "Support",
  range: ["next", "G1"],
  support: 164.96,
  hp: 1643,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 1643,
  currentHp: 1643,
  def: 0,
  cRate: 0,
  cDmg: 0,
  agi: 5,
  permDmgReduc: 0,
  addDmgReduc: 0,
  immunity: [false, false, false, false],
  prohibition: [false, false],
  dpsBuff: [0, 0, 0],
  healBuff: ["target", 15],
  dmgReducBuff: 5
};

var hyeonwul = {
  type: "Support",
  range: ["next", "F1"],
  support: 164.96,
  hp: 1989,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 1989,
  currentHp: 1989,
  def: 0,
  cRate: 0,
  cDmg: 0,
  agi: 10,
  permDmgReduc: 0,
  addDmgReduc: 0,
  immunity: [false, false, false, false],
  prohibition: [false, false],
  dpsBuff: [20, 15, 36],
  healBuff: [null, 0],
  dmgReducBuff: 0
};
