var sloan = {
  type: "Defense",
  range: ["front", "A0"],
  atk: 722,
  flatRuneAtk: 0,
  percRuneAtk: 0,
  currentAtk: 722,
  hp: 4492,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 4492,
  currentHp: 4492,
  def: 10,
  cRate: 5,
  cDmg: 50,
  agi: 0,
  extra: false,
  extraDmg: null,
  permDmgReduc: 0,
  addDmgReduc: 35,
  immunity: [false, false, false, false],
  prohibition: [false, false]
};

var carlson = {
  type: "Defense",
  range: ["front", "A0"],
  atk: 704,
  flatRuneAtk: 0,
  percRuneAtk: 0,
  currentAtk: 704,
  hp: 5478,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 5478,
  currentHp: 5478,
  def: 12,
  cRate: 10,
  cDmg: 50,
  agi: 0,
  extra: false,
  extraDmg: null,
  permDmgReduc: 0,
  addDmgReduc: 35,
  immunity: [false, false, false, false],
  prohibition: [false, false]
};

var cacey = {
  type: "Defense",
  range: ["front", "B1"],
  atk: 560,
  flatRuneAtk: 0,
  percRuneAtk: 0,
  currentAtk: 560,
  hp: 4123,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 4123,
  currentHp: 4123,
  def: 12,
  cRate: 10,
  cDmg: 50,
  agi: 0,
  extra: false,
  extraDmg: null,
  permDmgReduc: 0,
  addDmgReduc: 70,
  immunity: [false, false, false, false],
  prohibition: [false, false]
};

var tiara = {
  type: "Defense",
  range: ["front", "A0"],
  atk: 615,
  flatRuneAtk: 0,
  percRuneAtk: 0,
  currentAtk: 615,
  hp: 4081,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 4081,
  currentHp: 4081,
  def: 10,
  cRate: 10,
  cDmg: 50,
  agi: 0,
  extra: false,
  extraDmg: null,
  permDmgReduc: 0,
  addDmgReduc: 50,
  immunity: [false, false, false, false],
  prohibition: [false, false]
};

var tiara = {
  type: "Defense",
  range: ["front", "A0"],
  atk: 615,
  flatRuneAtk: 0,
  percRuneAtk: 0,
  currentAtk: 615,
  hp: 4081,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 4081,
  currentHp: 4081,
  def: 10,
  cRate: 10,
  cDmg: 50,
  agi: 0,
  extra: false,
  extraDmg: null,
  permDmgReduc: 0,
  addDmgReduc: 50,
  immunity: [false, false, false, false],
  prohibition: [false, false]
};

var horan = {
  type: "Defense",
  range: ["front", "A0"],
  atk: 804,
  flatRuneAtk: 0,
  percRuneAtk: 0,
  currentAtk: 804,
  hp: 3837,
  flatRuneHp: 0,
  percRuneHp: 0,
  maxHp: 3837,
  currentHp: 3837,
  def: 0,
  cRate: 10,
  cDmg: 50,
  agi: 20,
  extra: false,
  extraDmg: null,
  permDmgReduc: 30,
  addDmgReduc: 0,
  immunity: [false, false, false, false],
  prohibition: [false, false]
};
